# Preliminaries

In [5]:
import numpy as np

import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt

In [6]:
import glob
import os

In [12]:
import os
import pandas as pd
import glob

def simple_spreadsheet_scan(folder_path):
    """Simple version that just lists files and basic properties"""
    
    extensions = ['*.xlsx', '*.xls', '*.csv', '*.ods']
    files_found = []
    
    for ext in extensions:
        files_found.extend(glob.glob(os.path.join(folder_path, ext)))
    
    print(f"Found {len(files_found)} spreadsheet files:")
    print("-" * 60)
    
    for file_path in files_found:
        file_name = os.path.basename(file_path)
        file_size = os.path.getsize(file_path) / (1024 * 1024)  # MB
        file_ext = os.path.splitext(file_path)[1]
        
        print(f"📊 {file_name}")
        print(f"   Type: {file_ext}")
        print(f"   Size: {file_size:.2f} MB")
        print(f"   Path: {file_path}")
        print()

# Usage
folder_path = "mldataset"
simple_spreadsheet_scan(folder_path)

Found 22 spreadsheet files:
------------------------------------------------------------
📊 adolescent#001.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\adolescent#001.csv

📊 adolescent#003.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\adolescent#003.csv

📊 adolescent#004.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\adolescent#004.csv

📊 adolescent#005.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\adolescent#005.csv

📊 adolescent#006.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\adolescent#006.csv

📊 adolescent#009.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\adolescent#009.csv

📊 adolescent#010.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\adolescent#010.csv

📊 adult#001.csv
   Type: .csv
   Size: 0.15 MB
   Path: mldataset\adult#001.csv

📊 adult#002.csv
   Type: .csv
   Size: 0.15 MB
   Path: mldataset\adult#002.csv

📊 adult#003.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\adult#003.csv

📊 adult#004.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\adult#004.csv

📊 adult#005.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\adult#005.csv

📊 adult#006.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\adult#006.csv

📊 adult#007.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\adult#007.csv

📊 adult#008.csv
   Type: .csv
   Size: 0.15 MB
   Path: mldataset\adult#008.csv

📊 adult#009.csv
   Type: .csv
   Size: 0.15 MB
   Path: mldataset\adult#009.csv

📊 adult#010.csv
   Type: .csv
   Size: 0.15 MB
   Path: mldataset\adult#010.csv

📊 child#001.csv
   Type: .csv
   Size: 0.15 MB
   Path: mldataset\child#001.csv

📊 child#002.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\child#002.csv

📊 child#004.csv
   Type: .csv
   Size: 0.16 MB
   Path: mldataset\child#004.csv

📊 child#005.csv
   Type: .csv
   Size: 0.17 MB
   Path: mldataset\child#005.csv

📊 child#010.csv
   Type: .csv
   Size: 0.15 MB
   Path: mldataset\child#010.csv

In [13]:
import os
import pandas as pd
from openpyxl import load_workbook
import glob
from datetime import datetime

def get_spreadsheet_properties(folder_path):
    """
    Parse a folder and get properties of all spreadsheet files
    Supports: .xlsx, .xls, .csv, .ods
    """
    
    # Supported file extensions
    extensions = ['*.xlsx', '*.xls', '*.csv', '*.ods']
    spreadsheet_files = []
    
    # Find all spreadsheet files in the folder
    for ext in extensions:
        spreadsheet_files.extend(glob.glob(os.path.join(folder_path, ext)))
    
    if not spreadsheet_files:
        print("No spreadsheet files found in the specified folder.")
        return []
    
    spreadsheet_data = []
    
    for file_path in spreadsheet_files:
        try:
            file_info = get_file_properties(file_path)
            spreadsheet_data.append(file_info)
        except Exception as e:
            print(f"Error processing {file_path}: {str(e)}")
    
    return spreadsheet_data

def get_file_properties(file_path):
    """Get properties for a single spreadsheet file"""
    
    file_name = os.path.basename(file_path)
    file_size = os.path.getsize(file_path)
    file_extension = os.path.splitext(file_path)[1].lower()
    modified_time = datetime.fromtimestamp(os.path.getmtime(file_path))
    
    properties = {
        'file_name': file_name,
        'file_path': file_path,
        'file_size_bytes': file_size,
        'file_size_mb': round(file_size / (1024 * 1024), 2),
        'file_extension': file_extension,
        'last_modified': modified_time.strftime('%Y-%m-%d %H:%M:%S'),
        'sheets': [],
        'row_count': 0,
        'column_count': 0
    }
    
    try:
        if file_extension in ['.xlsx', '.xls']:
            properties.update(get_excel_properties(file_path))
        elif file_extension == '.csv':
            properties.update(get_csv_properties(file_path))
        elif file_extension == '.ods':
            properties.update(get_ods_properties(file_path))
    except Exception as e:
        properties['error'] = str(e)
    
    return properties

def get_excel_properties(file_path):
    """Get properties for Excel files"""
    properties = {}
    
    # Using openpyxl for metadata
    workbook = load_workbook(file_path, read_only=True)
    properties['sheets'] = workbook.sheetnames
    properties['sheet_count'] = len(workbook.sheetnames)
    
    # Get dimensions for each sheet
    sheet_info = []
    for sheet_name in workbook.sheetnames:
        sheet = workbook[sheet_name]
        sheet_info.append({
            'name': sheet_name,
            'rows': sheet.max_row,
            'columns': sheet.max_column
        })
    
    properties['sheet_details'] = sheet_info
    
    # Using pandas for data statistics
    try:
        excel_file = pd.ExcelFile(file_path)
        first_sheet_df = pd.read_excel(file_path, sheet_name=0, nrows=1)
        properties['column_count'] = len(first_sheet_df.columns)
        properties['columns_sample'] = first_sheet_df.columns.tolist()
    except:
        pass
    
    workbook.close()
    return properties

def get_csv_properties(file_path):
    """Get properties for CSV files"""
    properties = {}
    
    try:
        # Read first few rows to get structure
        df_sample = pd.read_csv(file_path, nrows=5)
        properties['row_count'] = sum(1 for line in open(file_path)) - 1  # Subtract header
        properties['column_count'] = len(df_sample.columns)
        properties['columns'] = df_sample.columns.tolist()
        properties['data_types'] = {col: str(dtype) for col, dtype in df_sample.dtypes.items()}
    except Exception as e:
        properties['error'] = f"CSV parsing error: {str(e)}"
    
    return properties

def get_ods_properties(file_path):
    """Get properties for ODS files"""
    properties = {}
    
    try:
        ods_file = pd.ExcelFile(file_path, engine='odf')
        properties['sheets'] = ods_file.sheet_names
        properties['sheet_count'] = len(ods_file.sheet_names)
        
        # Get first sheet info
        first_sheet_df = pd.read_excel(file_path, sheet_name=0, nrows=1, engine='odf')
        properties['column_count'] = len(first_sheet_df.columns)
        properties['columns_sample'] = first_sheet_df.columns.tolist()
    except Exception as e:
        properties['error'] = f"ODS parsing error: {str(e)}"
    
    return properties

def display_spreadsheet_info(spreadsheet_data):
    """Display the spreadsheet information in a readable format"""
    
    print("=" * 80)
    print("SPREADSHEET FOLDER ANALYSIS REPORT")
    print("=" * 80)
    
    for i, file_info in enumerate(spreadsheet_data, 1):
        print(f"\n{i}. FILE: {file_info['file_name']}")
        print(f"   Path: {file_info['file_path']}")
        print(f"   Size: {file_info['file_size_mb']} MB ({file_info['file_size_bytes']} bytes)")
        print(f"   Type: {file_info['file_extension']}")
        print(f"   Last Modified: {file_info['last_modified']}")
        
        if 'sheet_count' in file_info:
            print(f"   Sheets: {file_info['sheet_count']}")
            print(f"   Sheet Names: {', '.join(file_info['sheets'])}")
            
            if 'sheet_details' in file_info:
                print("   Sheet Details:")
                for sheet in file_info['sheet_details']:
                    print(f"     - {sheet['name']}: {sheet['rows']} rows, {sheet['columns']} columns")
        
        if 'column_count' in file_info and file_info['column_count'] > 0:
            print(f"   Columns: {file_info['column_count']}")
            if 'columns_sample' in file_info:
                print(f"   Column Names: {file_info['columns_sample']}")
        
        if 'error' in file_info:
            print(f"   ⚠️  Error: {file_info['error']}")
        
        print("-" * 80)

# Usage example
if __name__ == "__main__":
    # Specify your folder path here
    folder_path = input("Enter the folder path: ").strip()
    
    # Remove quotes if user pasted path with quotes
    folder_path = folder_path.strip('"\'')
    
    if not os.path.exists(folder_path):
        print("Folder path does not exist!")
    else:
        spreadsheet_data = get_spreadsheet_properties(folder_path)
        display_spreadsheet_info(spreadsheet_data)

Enter the folder path:  mldataset

================================================================================
SPREADSHEET FOLDER ANALYSIS REPORT
================================================================================

1. FILE: adolescent#001.csv
   Path: mldataset\adolescent#001.csv
   Size: 0.17 MB (180986 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

2. FILE: adolescent#003.csv
   Path: mldataset\adolescent#003.csv
   Size: 0.17 MB (179550 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

3. FILE: adolescent#004.csv
   Path: mldataset\adolescent#004.csv
   Size: 0.17 MB (178638 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

4. FILE: adolescent#005.csv
   Path: mldataset\adolescent#005.csv
   Size: 0.17 MB (179324 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

5. FILE: adolescent#006.csv
   Path: mldataset\adolescent#006.csv
   Size: 0.17 MB (180164 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

6. FILE: adolescent#009.csv
   Path: mldataset\adolescent#009.csv
   Size: 0.17 MB (178819 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

7. FILE: adolescent#010.csv
   Path: mldataset\adolescent#010.csv
   Size: 0.17 MB (179054 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

8. FILE: adult#001.csv
   Path: mldataset\adult#001.csv
   Size: 0.15 MB (161433 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

9. FILE: adult#002.csv
   Path: mldataset\adult#002.csv
   Size: 0.15 MB (161688 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

10. FILE: adult#003.csv
   Path: mldataset\adult#003.csv
   Size: 0.17 MB (179491 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

11. FILE: adult#004.csv
   Path: mldataset\adult#004.csv
   Size: 0.17 MB (179463 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

12. FILE: adult#005.csv
   Path: mldataset\adult#005.csv
   Size: 0.17 MB (178987 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

13. FILE: adult#006.csv
   Path: mldataset\adult#006.csv
   Size: 0.17 MB (177857 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

14. FILE: adult#007.csv
   Path: mldataset\adult#007.csv
   Size: 0.17 MB (179135 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

15. FILE: adult#008.csv
   Path: mldataset\adult#008.csv
   Size: 0.15 MB (161622 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

16. FILE: adult#009.csv
   Path: mldataset\adult#009.csv
   Size: 0.15 MB (156171 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

17. FILE: adult#010.csv
   Path: mldataset\adult#010.csv
   Size: 0.15 MB (161981 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

18. FILE: child#001.csv
   Path: mldataset\child#001.csv
   Size: 0.15 MB (156233 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

19. FILE: child#002.csv
   Path: mldataset\child#002.csv
   Size: 0.17 MB (178127 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

20. FILE: child#004.csv
   Path: mldataset\child#004.csv
   Size: 0.16 MB (171610 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

21. FILE: child#005.csv
   Path: mldataset\child#005.csv
   Size: 0.17 MB (176217 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

22. FILE: child#010.csv
   Path: mldataset\child#010.csv
   Size: 0.15 MB (162076 bytes)
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Columns: 8
--------------------------------------------------------------------------------

In [14]:
import os
import pandas as pd
from openpyxl import load_workbook
import glob
from datetime import datetime

def parse_spreadsheet_folder(folder_path):
    """
    Parse a folder containing spreadsheets and create DataFrames for CSV files
    Returns: 
    - spreadsheet_properties: List of file properties
    - dataframes_dict: Dictionary of DataFrames (for CSV files)
    """
    
    # Supported file extensions
    extensions = ['*.xlsx', '*.xls', '*.csv', '*.ods']
    spreadsheet_files = []
    
    # Find all spreadsheet files in the folder
    for ext in extensions:
        spreadsheet_files.extend(glob.glob(os.path.join(folder_path, ext)))
    
    if not spreadsheet_files:
        print("No spreadsheet files found in the specified folder.")
        return [], {}
    
    spreadsheet_properties = []
    dataframes_dict = {}
    
    for file_path in spreadsheet_files:
        try:
            # Get file properties
            file_info = get_file_properties(file_path)
            spreadsheet_properties.append(file_info)
            
            # Create DataFrame for CSV files
            if file_info['file_extension'] == '.csv':
                df = create_dataframe_from_csv(file_path)
                if df is not None:
                    # Use filename without extension as key
                    file_key = os.path.splitext(file_info['file_name'])[0]
                    dataframes_dict[file_key] = df
                    file_info['dataframe_created'] = True
                    file_info['dataframe_shape'] = df.shape
                else:
                    file_info['dataframe_created'] = False
            else:
                file_info['dataframe_created'] = "Only CSV files are auto-converted to DataFrames"
                
        except Exception as e:
            print(f"Error processing {file_path}: {str(e)}")
    
    return spreadsheet_properties, dataframes_dict

def get_file_properties(file_path):
    """Get properties for a single spreadsheet file"""
    
    file_name = os.path.basename(file_path)
    file_size = os.path.getsize(file_path)
    file_extension = os.path.splitext(file_path)[1].lower()
    modified_time = datetime.fromtimestamp(os.path.getmtime(file_path))
    
    properties = {
        'file_name': file_name,
        'file_path': file_path,
        'file_size_bytes': file_size,
        'file_size_mb': round(file_size / (1024 * 1024), 2),
        'file_extension': file_extension,
        'last_modified': modified_time.strftime('%Y-%m-%d %H:%M:%S'),
        'sheets': [],
        'row_count': 0,
        'column_count': 0
    }
    
    try:
        if file_extension in ['.xlsx', '.xls']:
            properties.update(get_excel_properties(file_path))
        elif file_extension == '.csv':
            properties.update(get_csv_properties(file_path))
        elif file_extension == '.ods':
            properties.update(get_ods_properties(file_path))
    except Exception as e:
        properties['error'] = str(e)
    
    return properties

def get_csv_properties(file_path):
    """Get properties for CSV files"""
    properties = {}
    
    try:
        # Read first few rows to get structure
        df_sample = pd.read_csv(file_path, nrows=5)
        properties['row_count'] = sum(1 for line in open(file_path)) - 1  # Subtract header
        properties['column_count'] = len(df_sample.columns)
        properties['columns'] = df_sample.columns.tolist()
        properties['data_types'] = {col: str(dtype) for col, dtype in df_sample.dtypes.items()}
        
        # Additional CSV-specific properties
        with open(file_path, 'r') as f:
            first_line = f.readline()
            properties['delimiter'] = 'comma'  # Default, can be enhanced to detect actual delimiter
            properties['encoding'] = 'utf-8'   # Default, can be enhanced to detect encoding
    except Exception as e:
        properties['error'] = f"CSV parsing error: {str(e)}"
    
    return properties

def create_dataframe_from_csv(file_path, **kwargs):
    """
    Create a DataFrame from a CSV file with error handling
    
    Parameters:
    - file_path: Path to the CSV file
    - **kwargs: Additional pandas read_csv parameters
    
    Returns:
    - DataFrame if successful, None if failed
    """
    try:
        # Try reading with default parameters first
        df = pd.read_csv(file_path, **kwargs)
        print(f"✅ Successfully created DataFrame from {os.path.basename(file_path)}")
        print(f"   Shape: {df.shape}")
        return df
    except Exception as e:
        print(f"❌ Error reading {file_path}: {str(e)}")
        
        # Try alternative encodings if UTF-8 fails
        encodings = ['latin-1', 'iso-8859-1', 'cp1252']
        for encoding in encodings:
            try:
                df = pd.read_csv(file_path, encoding=encoding, **kwargs)
                print(f"✅ Successfully read with {encoding} encoding")
                print(f"   Shape: {df.shape}")
                return df
            except:
                continue
        
        print(f"❌ Failed to read {file_path} with all attempted encodings")
        return None

def get_excel_properties(file_path):
    """Get properties for Excel files"""
    properties = {}
    
    workbook = load_workbook(file_path, read_only=True)
    properties['sheets'] = workbook.sheetnames
    properties['sheet_count'] = len(workbook.sheetnames)
    
    sheet_info = []
    for sheet_name in workbook.sheetnames:
        sheet = workbook[sheet_name]
        sheet_info.append({
            'name': sheet_name,
            'rows': sheet.max_row,
            'columns': sheet.max_column
        })
    
    properties['sheet_details'] = sheet_info
    
    try:
        excel_file = pd.ExcelFile(file_path)
        first_sheet_df = pd.read_excel(file_path, sheet_name=0, nrows=1)
        properties['column_count'] = len(first_sheet_df.columns)
        properties['columns_sample'] = first_sheet_df.columns.tolist()
    except:
        pass
    
    workbook.close()
    return properties

def get_ods_properties(file_path):
    """Get properties for ODS files"""
    properties = {}
    
    try:
        ods_file = pd.ExcelFile(file_path, engine='odf')
        properties['sheets'] = ods_file.sheet_names
        properties['sheet_count'] = len(ods_file.sheet_names)
        
        first_sheet_df = pd.read_excel(file_path, sheet_name=0, nrows=1, engine='odf')
        properties['column_count'] = len(first_sheet_df.columns)
        properties['columns_sample'] = first_sheet_df.columns.tolist()
    except Exception as e:
        properties['error'] = f"ODS parsing error: {str(e)}"
    
    return properties

def display_spreadsheet_info(spreadsheet_properties, dataframes_dict):
    """Display the spreadsheet information and DataFrame details"""
    
    print("=" * 80)
    print("SPREADSHEET FOLDER ANALYSIS REPORT")
    print("=" * 80)
    
    for i, file_info in enumerate(spreadsheet_properties, 1):
        print(f"\n{i}. FILE: {file_info['file_name']}")
        print(f"   Path: {file_info['file_path']}")
        print(f"   Size: {file_info['file_size_mb']} MB")
        print(f"   Type: {file_info['file_extension']}")
        print(f"   Last Modified: {file_info['last_modified']}")
        
        if file_info['file_extension'] == '.csv':
            print(f"   Rows: {file_info.get('row_count', 'N/A')}")
            print(f"   Columns: {file_info.get('column_count', 'N/A')}")
            if 'columns' in file_info:
                print(f"   Column Names: {file_info['columns'][:5]}...")  # Show first 5 columns
        
        if 'dataframe_created' in file_info:
            if file_info['dataframe_created'] is True:
                print(f"   ✅ DataFrame Created: Yes")
                print(f"   DataFrame Shape: {file_info.get('dataframe_shape', 'N/A')}")
            else:
                print(f"   ❌ DataFrame Created: No")
        
        if 'error' in file_info:
            print(f"   ⚠️  Error: {file_info['error']}")
        
        print("-" * 80)
    
    # Display DataFrame summary
    if dataframes_dict:
        print(f"\n📊 DATA FRAMES CREATED ({len(dataframes_dict)}):")
        print("=" * 50)
        for df_name, df in dataframes_dict.items():
            print(f"\nDataFrame: '{df_name}'")
            print(f"Shape: {df.shape}")
            print(f"Columns: {list(df.columns)}")
            print(f"Memory Usage: {df.memory_usage(deep=True).sum() / 1024 ** 2:.2f} MB")
            print(f"First 3 rows:")
            print(df.head(3))
            print("-" * 40)

# Advanced function to create DataFrames from specific sheets in Excel files
def create_dataframes_from_excel(file_path, sheet_names=None):
    """
    Create DataFrames from specific sheets in an Excel file
    
    Parameters:
    - file_path: Path to Excel file
    - sheet_names: List of sheet names to read (if None, reads all sheets)
    
    Returns:
    - Dictionary of DataFrames with sheet names as keys
    """
    try:
        if sheet_names is None:
            # Read all sheets
            dfs = pd.read_excel(file_path, sheet_name=None)
        else:
            # Read specific sheets
            dfs = {}
            for sheet in sheet_names:
                dfs[sheet] = pd.read_excel(file_path, sheet_name=sheet)
        
        print(f"✅ Created {len(dfs)} DataFrames from {os.path.basename(file_path)}")
        return dfs
    except Exception as e:
        print(f"❌ Error reading Excel file {file_path}: {str(e)}")
        return {}

# Usage example
if __name__ == "__main__":
    # Specify your folder path here
    folder_path = input("Enter the folder path: ").strip()
    folder_path = folder_path.strip('"\'')
    
    if not os.path.exists(folder_path):
        print("Folder path does not exist!")
    else:
        # Get properties and create DataFrames for CSV files
        spreadsheet_properties, dataframes_dict = parse_spreadsheet_folder(folder_path)
        
        # Display results
        display_spreadsheet_info(spreadsheet_properties, dataframes_dict)
        
        # Now you can work with the DataFrames
        print(f"\n🎯 ACCESSING YOUR DATA FRAMES:")
        print("=" * 40)
        
        for df_name, df in dataframes_dict.items():
            print(f"\nDataFrame: {df_name}")
            print(f"Available as: dataframes_dict['{df_name}']")
            print(f"Shape: {df.shape}")
            
            # Example: Show basic statistics for numeric columns
            numeric_cols = df.select_dtypes(include=['number']).columns
            if len(numeric_cols) > 0:
                print(f"Numeric columns: {list(numeric_cols)}")
        
        # Example of how to use the DataFrames
        if dataframes_dict:
            print(f"\n💡 EXAMPLE USAGE:")
            first_df_name = list(dataframes_dict.keys())[0]
            first_df = dataframes_dict[first_df_name]
            print(f"# Access first DataFrame: dataframes_dict['{first_df_name}']")
            print(f"# Get shape: dataframes_dict['{first_df_name}'].shape")
            print(f"# Get columns: dataframes_dict['{first_df_name}'].columns.tolist()")
            print(f"# Show first 5 rows: dataframes_dict['{first_df_name}'].head()")

Enter the folder path:  mldataset

✅ Successfully created DataFrame from adolescent#001.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adolescent#003.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adolescent#004.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adolescent#005.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adolescent#006.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adolescent#009.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adolescent#010.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adult#001.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adult#002.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adult#003.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adult#004.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adult#005.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adult#006.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adult#007.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adult#008.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adult#009.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from adult#010.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from child#001.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from child#002.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from child#004.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from child#005.csv
   Shape: (1440, 8)
✅ Successfully created DataFrame from child#010.csv
   Shape: (1440, 8)
================================================================================
SPREADSHEET FOLDER ANALYSIS REPORT
================================================================================

1. FILE: adolescent#001.csv
   Path: mldataset\adolescent#001.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

2. FILE: adolescent#003.csv
   Path: mldataset\adolescent#003.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

3. FILE: adolescent#004.csv
   Path: mldataset\adolescent#004.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

4. FILE: adolescent#005.csv
   Path: mldataset\adolescent#005.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

5. FILE: adolescent#006.csv
   Path: mldataset\adolescent#006.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

6. FILE: adolescent#009.csv
   Path: mldataset\adolescent#009.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

7. FILE: adolescent#010.csv
   Path: mldataset\adolescent#010.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

8. FILE: adult#001.csv
   Path: mldataset\adult#001.csv
   Size: 0.15 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

9. FILE: adult#002.csv
   Path: mldataset\adult#002.csv
   Size: 0.15 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

10. FILE: adult#003.csv
   Path: mldataset\adult#003.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

11. FILE: adult#004.csv
   Path: mldataset\adult#004.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

12. FILE: adult#005.csv
   Path: mldataset\adult#005.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

13. FILE: adult#006.csv
   Path: mldataset\adult#006.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

14. FILE: adult#007.csv
   Path: mldataset\adult#007.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

15. FILE: adult#008.csv
   Path: mldataset\adult#008.csv
   Size: 0.15 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

16. FILE: adult#009.csv
   Path: mldataset\adult#009.csv
   Size: 0.15 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

17. FILE: adult#010.csv
   Path: mldataset\adult#010.csv
   Size: 0.15 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

18. FILE: child#001.csv
   Path: mldataset\child#001.csv
   Size: 0.15 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

19. FILE: child#002.csv
   Path: mldataset\child#002.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

20. FILE: child#004.csv
   Path: mldataset\child#004.csv
   Size: 0.16 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

21. FILE: child#005.csv
   Path: mldataset\child#005.csv
   Size: 0.17 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

22. FILE: child#010.csv
   Path: mldataset\child#010.csv
   Size: 0.15 MB
   Type: .csv
   Last Modified: 2025-09-05 01:55:56
   Rows: 1440
   Columns: 8
   Column Names: ['Time', 'BG', 'CGM', 'CHO', 'insulin']...
   ✅ DataFrame Created: Yes
   DataFrame Shape: (1440, 8)
--------------------------------------------------------------------------------

📊 DATA FRAMES CREATED (22):
==================================================

DataFrame: 'adolescent#001'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM  CHO   insulin  LBGI      HBGI  \
0  2023-10-25 06:00:00  126.013943  136.435033  0.0  0.013933   0.0  0.446600
1  2023-10-25 06:05:00  126.589661  137.121412  0.0  0.013933   0.0  0.483302
2  2023-10-25 06:10:00  127.155902  138.398018  0.0  0.013933   0.0  0.520644

       Risk
0  0.446600
1  0.483302
2  0.520644
----------------------------------------

DataFrame: 'adolescent#003'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM  CHO   insulin      LBGI  HBGI  \
0  2023-10-25 06:00:00  109.517983  119.945975  0.0  0.541233  0.025342   0.0
1  2023-10-25 06:05:00  110.138546  120.646479  0.0  0.010800  0.015852   0.0
2  2023-10-25 06:10:00  111.189382  122.189594  0.0  0.010800  0.004895   0.0

       Risk
0  0.025342
1  0.015852
2  0.004895
----------------------------------------

DataFrame: 'adolescent#004'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM  CHO   insulin      LBGI  HBGI  \
0  2023-10-25 06:00:00   99.990043  110.393647  0.0  0.014558  0.482865   0.0
1  2023-10-25 06:05:00  100.612495  111.125249  0.0  0.014558  0.433474   0.0
2  2023-10-25 06:10:00  101.229304  112.450884  0.0  0.014558  0.387431   0.0

       Risk
0  0.482865
1  0.433474
2  0.387431
----------------------------------------

DataFrame: 'adolescent#005'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM  CHO   insulin  LBGI      HBGI  \
0  2023-10-25 06:00:00  117.189411  127.669570  0.0  0.012042   0.0  0.057526
1  2023-10-25 06:05:00  117.620714  128.209905  0.0  0.012042   0.0  0.068388
2  2023-10-25 06:10:00  118.046616  129.344541  0.0  0.012042   0.0  0.079993

       Risk
0  0.057526
1  0.068388
2  0.079993
----------------------------------------

DataFrame: 'adolescent#006'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM  CHO   insulin  LBGI      HBGI  \
0  2023-10-25 06:00:00  134.219406  144.863792  0.0  0.014592   0.0  1.083660
1  2023-10-25 06:05:00  134.243316  144.995144  0.0  0.014592   0.0  1.085854
2  2023-10-25 06:10:00  134.265938  145.724843  0.0  0.014592   0.0  1.087931

       Risk
0  1.083660
1  1.085854
2  1.087931
----------------------------------------

DataFrame: 'adolescent#009'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM  CHO   insulin  LBGI      HBGI  \
0  2023-10-25 06:00:00  116.518851  126.968519  0.0  0.010108   0.0  0.042438
1  2023-10-25 06:05:00  117.023291  127.583535  0.0  0.010108   0.0  0.053583
2  2023-10-25 06:10:00  117.518585  128.789050  0.0  0.010108   0.0  0.065735

       Risk
0  0.042438
1  0.053583
2  0.065735
----------------------------------------

DataFrame: 'adolescent#010'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM  CHO   insulin  LBGI      HBGI  \
0  2023-10-25 06:00:00  117.404494  127.866384  0.0  0.013117   0.0  0.062830
1  2023-10-25 06:05:00  117.880961  128.452136  0.0  0.013117   0.0  0.075376
2  2023-10-25 06:10:00  118.351446  129.631583  0.0  0.013117   0.0  0.088829

       Risk
0  0.062830
1  0.075376
2  0.088829
----------------------------------------

DataFrame: 'adult#001'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time         BG        CGM   CHO   insulin       LBGI  HBGI  \
0  2023-10-25 06:00:00  58.805622  69.190114   0.0  0.021125  14.446750   0.0
1  2023-10-25 06:05:00  59.480598  69.971869  11.6  0.021125  13.946134   0.0
2  2023-10-25 06:10:00  60.155888  71.353649   0.0  1.181125  13.459509   0.0

        Risk
0  14.446750
1  13.946134
2  13.459509
----------------------------------------

DataFrame: 'adult#002'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time         BG        CGM  CHO   insulin      LBGI  HBGI  \
0  2023-10-25 06:00:00  86.116891  96.657960  0.0  0.022825  2.471340   0.0
1  2023-10-25 06:05:00  86.401104  97.048611  0.0  0.022825  2.410959   0.0
2  2023-10-25 06:10:00  86.686430  98.040064  0.0  0.022825  2.351285   0.0

       Risk
0  2.471340
1  2.410959
2  2.351285
----------------------------------------

DataFrame: 'adult#003'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM  CHO   insulin  LBGI      HBGI  \
0  2023-10-25 06:00:00  132.283325  142.767144  9.2  0.023758   0.0  0.912234
1  2023-10-25 06:05:00  132.706141  143.299516  0.0  1.045983   0.0  0.948617
2  2023-10-25 06:10:00  133.278789  144.501206  0.0  0.023758   0.0  0.998839

       Risk
0  0.912234
1  0.948617
2  0.998839
----------------------------------------

DataFrame: 'adult#004'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM   CHO  insulin  LBGI      HBGI  \
0  2023-10-25 06:00:00  126.171816  136.641708   0.0   0.0148   0.0  0.456537
1  2023-10-25 06:05:00  126.626869  137.206749   0.0   0.0148   0.0  0.485718
2  2023-10-25 06:10:00  127.074279  138.363776  10.4   0.0148   0.0  0.515186

       Risk
0  0.456537
1  0.485718
2  0.515186
----------------------------------------

DataFrame: 'adult#005'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM  CHO   insulin  LBGI      HBGI  \
0  2023-10-25 06:00:00  113.730627  124.101121  0.0  0.019667   0.0  0.003996
1  2023-10-25 06:05:00  114.429065  124.912102  0.0  0.019667   0.0  0.009861
2  2023-10-25 06:10:00  115.113513  126.308701  0.0  0.019667   0.0  0.018079

       Risk
0  0.003996
1  0.009861
2  0.018079
----------------------------------------

DataFrame: 'adult#006'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM  CHO   insulin      LBGI  HBGI  \
0  2023-10-25 06:00:00  105.032696  115.551162  0.0  0.028742  0.164363   0.0
1  2023-10-25 06:05:00  105.370430  115.996828  0.0  0.028742  0.149398   0.0
2  2023-10-25 06:10:00  105.705555  117.039566  0.0  0.028742  0.135298   0.0

       Risk
0  0.164363
1  0.149398
2  0.135298
----------------------------------------

DataFrame: 'adult#007'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM  CHO   insulin      LBGI  HBGI  \
0  2023-10-25 06:00:00  105.323161  115.779695  0.0  0.022858  0.151447   0.0
1  2023-10-25 06:05:00  105.812984  116.378820  0.0  0.022858  0.130935   0.0
2  2023-10-25 06:10:00  106.296785  117.571599  0.0  0.022858  0.112221   0.0

       Risk
0  0.151447
1  0.130935
2  0.112221
----------------------------------------

DataFrame: 'adult#008'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time         BG        CGM  CHO   insulin       LBGI  HBGI  \
0  2023-10-25 06:00:00  48.913127  59.295934  0.0  0.019025  23.725827   0.0
1  2023-10-25 06:05:00  49.603992  60.087747  0.0  0.019025  22.940123   0.0
2  2023-10-25 06:10:00  50.309086  61.493782  0.0  0.019025  22.162563   0.0

        Risk
0  23.725827
1  22.940123
2  22.162563
----------------------------------------

DataFrame: 'adult#009'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time         BG        CGM  CHO  insulin       LBGI  HBGI  \
0  2023-10-25 06:00:00  40.449098  50.727207  0.0   0.0189  35.643786   0.0
1  2023-10-25 06:05:00  41.394594  51.777205  0.0   0.0189  34.068256   0.0
2  2023-10-25 06:10:00  42.345610  53.432628  0.0   0.0189  32.553359   0.0

        Risk
0  35.643786
1  34.068256
2  32.553359
----------------------------------------

DataFrame: 'adult#010'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM  CHO   insulin      LBGI  HBGI  \
0  2023-10-25 06:00:00  108.460581  118.834274  0.0  0.016975  0.046801   0.0
1  2023-10-25 06:05:00  109.159961  119.641732  0.0  0.016975  0.031854   0.0
2  2023-10-25 06:10:00  109.856106  121.045767  0.0  0.016975  0.019890   0.0

       Risk
0  0.046801
1  0.031854
2  0.019890
----------------------------------------

DataFrame: 'child#001'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time          BG         CGM  CHO   insulin      LBGI  HBGI  \
0  2023-10-25 06:00:00  104.216396  114.591591  0.0  0.006575  0.203706   0.0
1  2023-10-25 06:05:00  104.905107  115.391832  0.0  0.006575  0.170215   0.0
2  2023-10-25 06:10:00  105.582352  116.780220  0.0  0.006575  0.140396   0.0

       Risk
0  0.203706
1  0.170215
2  0.140396
----------------------------------------

DataFrame: 'child#002'
Shape: (1440, 8)
Columns: ['Time', 'BG', 'CGM', 'CHO', 'insulin', 'LBGI', 'HBGI', 'Risk']
Memory Usage: 0.17 MB
First 3 rows:
                  Time         BG        CGM  CHO   insulin      LBGI  HBGI  \

In [ ]:
adolescent#001.csv

In [7]:
# get all spreadsheet files in the folder

folder_path = 'mldataset'
spreadsheet_files = glob.glob(os.path.join(folder_path, '*.csv'))

#Create list of DataFrames
dataframes_list = [pd.read_csv(file) for file in spreadsheet_files]

In [10]:
dataframes_list[0]

,Time,BG,CGM,CHO,insulin,LBGI,HBGI,Risk
0,2023-10-25 06:00:00,126.013943,136.435033,0.0,0.013933,0.0,0.446600,0.446600
1,2023-10-25 06:05:00,126.589661,137.121412,0.0,0.013933,0.0,0.483302,0.483302
2,2023-10-25 06:10:00,127.155902,138.398018,0.0,0.013933,0.0,0.520644,0.520644
3,2023-10-25 06:15:00,127.712577,140.060899,0.0,0.013933,0.0,0.558542,0.558542
4,2023-10-25 06:20:00,128.259611,141.830932,0.0,0.013933,0.0,0.596914,0.596914
...,...,...,...,...,...,...,...,...
1435,2023-10-30 05:35:00,123.071909,119.250427,0.0,0.013933,0.0,0.279643,0.279643
1436,2023-10-30 05:40:00,123.667039,120.113806,0.0,0.013933,0.0,0.310569,0.310569
1437,2023-10-30 05:45:00,124.254709,120.864200,11.6,0.013933,0.0,0.342545,0.342545
1438,2023-10-30 05:50:00,124.834743,121.494518,0.0,0.980600,0.0,0.375486,0.375486
1439,2023-10-30 05:55:00,125.407759,122.006210,0.0,0.013933,0.0,0.409355,0.409355

In [2]:
import pandas as pd
import glob

# Path to your folder
#folder_path = ""

# Get list of all CSV files in that folder
csv_files = glob.glob("/*.csv")

# Create a list to store DataFrames
dfs = ['adult#001', 'adult#002',]

# Loop through each file and read into DataFrame
for file in csv_files:
    df = pd.read_csv(file)
    dfs.append(df)

# Now dfs[0], dfs[1], ... contain your DataFrames

NameError: name 'df0' is not defined

In [4]:
teen1 = pd.read_csv("adolescent#001.csv")

teen1

,Time,BG,CGM,CHO,insulin,LBGI,HBGI,Risk
0,2023-10-25 06:00:00,126.013943,136.435033,0.0,0.013933,0.0,0.446600,0.446600
1,2023-10-25 06:05:00,126.589661,137.121412,0.0,0.013933,0.0,0.483302,0.483302
2,2023-10-25 06:10:00,127.155902,138.398018,0.0,0.013933,0.0,0.520644,0.520644
3,2023-10-25 06:15:00,127.712577,140.060899,0.0,0.013933,0.0,0.558542,0.558542
4,2023-10-25 06:20:00,128.259611,141.830932,0.0,0.013933,0.0,0.596914,0.596914
...,...,...,...,...,...,...,...,...
1435,2023-10-30 05:35:00,123.071909,119.250427,0.0,0.013933,0.0,0.279643,0.279643
1436,2023-10-30 05:40:00,123.667039,120.113806,0.0,0.013933,0.0,0.310569,0.310569
1437,2023-10-30 05:45:00,124.254709,120.864200,11.6,0.013933,0.0,0.342545,0.342545
1438,2023-10-30 05:50:00,124.834743,121.494518,0.0,0.980600,0.0,0.375486,0.375486
1439,2023-10-30 05:55:00,125.407759,122.006210,0.0,0.013933,0.0,0.409355,0.409355

In [10]:
teen1 = pd.read_csv("ML2324_CW_DataSet_Initial\adolescent#001.csv")
'''
teen3 = pd.read_csv('/content/adolescent#003.csv')

teen4 = pd.read_csv('/content/adolescent#004.csv')

teen5 = pd.read_csv('/content/adolescent#005.csv')

teen6 = pd.read_csv('/content/adolescent#006.csv')

teen9 = pd.read_csv('/content/adolescent#009.csv')

teen10 = pd.read_csv('/content/adolescent#010.csv')

##############################################################

adult1 = pd.read_csv('/content/adult#001.csv')

adult2 = pd.read_csv('/content/adult#002.csv')

adult3 = pd.read_csv('/content/adult#003.csv')

adult4 = pd.read_csv('/content/adult#004.csv')

adult5 = pd.read_csv('/content/adult#005.csv')

adult6 = pd.read_csv('/content/adult#006.csv')

adult7 = pd.read_csv('/content/adult#007.csv')

adult8 = pd.read_csv('/content/adult#008.csv')

adult9 = pd.read_csv('/content/adult#009.csv')

adult10 = pd.read_csv('/content/adult#010.csv')

###################################################################


child1 = pd.read_csv('/content/child#001.csv')

child2 = pd.read_csv('/content/child#002.csv')

child4 = pd.read_csv('/content/child#004.csv')

child5 = pd.read_csv('/content/child#005.csv')

child10 = pd.read_csv('/content/child#010.csv')
'''

OSError: [Errno 22] Invalid argument: 'ML2324_CW_DataSet_Initial\x07dolescent#001.csv'

In [8]:
teen1

NameError: name 'teen1' is not defined

In [ ]:
child10

In [ ]:
# Define all variables in a dictionary with their names as keys
pateints = {
    "child1": child1,
    "child2": child2,
    "child4": child4,
    "child5": child5,
    "child10": child10,
    "teen1": teen1,
    "teen3": teen3,
    "teen4": teen4,
    "teen5": teen5,
    "teen6": teen6,
    "teen9": teen9,
    "teen10": teen10,
    "adult1": adult1,
    "adult2": adult2,
    "adult3": adult3,
    "adult4": adult4,
    "adult5": adult5,
    "adult6": adult6,
    "adult7": adult7,
    "adult8": adult8,
    "adult9": adult9,
    "adult10": adult10,

}

# Iterate through the dictionary and print the names and shapes
for name, df in pateints.items():
    print(f"{name} shape: {df.shape}")

In [ ]:
# Define all variables in a dictionary with their names as keys
pateints_time = {
    "child1": child1['Time'],
    "child2": child2['Time'],
    "child4": child4['Time'],
    "child5": child5['Time'],
    "child10": child10['Time'],
    "teen1": teen1['Time'],
    "teen3": teen3['Time'],
    "teen4": teen4['Time'],
    "teen5": teen5['Time'],
    "teen6": teen6['Time'],
    "teen9": teen9['Time'],
    "teen10": teen10['Time'],
    "adult1": adult1['Time'],
    "adult2": adult2['Time'],
    "adult3": adult3['Time'],
    "adult4": adult4['Time'],
    "adult5": adult5['Time'],
    "adult6": adult6['Time'],
    "adult7": adult7['Time'],
    "adult8": adult8['Time'],
    "adult9": adult9['Time'],
    "adult10": adult10['Time']

}



'''
# Iterate through the dictionary and print the names and shapes
for name, df in pateints.items():
    print(f"{name} shape: {df.shape}")
'''

In [ ]:
time_df = pd.DataFrame.from_dict(pateints_time)

time_df

In [ ]:
time_df['child1']

In [ ]:
# Get unique values row-wise
#time_df["unique_values"] = time_df.apply(lambda row: list(set(row)), axis=1)

time_df["unique_values"]

In [ ]:
# Count unique values in each row
time_df["unique_count"] = time_df.apply(lambda row: len(set(row)), axis=1)

# Filter rows with more than 1 unique value
#rows_with_multiple_unique = time_df[time_df["unique_count"] > 1]

In [ ]:
time_df.dtypes

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Example data: Last 24 hours of CGM and insulin intake data
# This would ideally be real data from a CSV or database
data = {
    'time': pd.date_range(start='2025-08-29', periods=288, freq='5T'),  # 288 samples for 24 hours
    'CGM': np.random.randint(80, 200, 288),  # Random CGM values between 80 and 200
    'insulin': np.random.uniform(1, 10, 288)  # Random insulin intake values between 1 and 10 units
}

df = pd.DataFrame(data)

# For simplicity, assume hypoglycemia occurs if CGM < 70
df['hypoglycemia'] = np.where(df['CGM'] < 70, 1, 0)

# Let's use the last 24 hours of data to predict the next 2 hours
# Extracting features: mean, min, max, std for CGM and insulin over the last 24 hours
def create_features(df, window_size=24):
    features = []
    labels = []

    for i in range(window_size, len(df) - 2):  # The last 2 hours for prediction
        window_cgm = df['CGM'][i-window_size:i]
        window_insulin = df['insulin'][i-window_size:i]

        # Create features: Mean, max, and std for CGM and insulin over the past 24 hours
        mean_cgm = window_cgm.mean()
        max_cgm = window_cgm.max()
        std_cgm = window_cgm.std()
        mean_insulin = window_insulin.mean()
        max_insulin = window_insulin.max()

        features.append([mean_cgm, max_cgm, std_cgm, mean_insulin, max_insulin])

        # The label is whether hypoglycemia will happen in the next 2 hours
        labels.append(df['hypoglycemia'][i+2])  # Prediction for the next 2 hours

    return np.array(features), np.array(labels)

# Create features and labels
X, y = create_features(df)

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train a Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))